- name: "A-Timesheet-1"
  description: "Log any time spent on this into the A-Timesheet-1 project"
  color: "#5319E7"
- name: "backport staging"
  description: "Label to automatically backport PR to staging branch"
  color: "#B60205"
- name: "Dependencies"
  description: "Pull requests that update a dependency file"
  color: "#0366d6"
- name: "Sponsored"
  color: "#b506d8"
- name: "T-Deprecation"
  description: "A pull request that makes something deprecated"
  color: "#98e6ae"
- name: "X-Blocked"
  description: "The PR cannot move forward in any capacity until an action is made"
  color: "ff7979"
- name: "X-Breaking-Change"
  color: "#ff7979"
- name: "X-Upcoming-Release-Blocker"
  description: "This does not affect the current release cycle but will affect the next one"
  color: "#e99695"
- name: "Z-Community-PR"
  description: "Issue is solved by a community member's PR"
  color: "#ededed"
- name: "Z-Experiment"
  description: "Experimental PR, primarily up for its Netlify build, high likelihood of never making it beyond here."
  color: "#b60205"
